name: bowtie_index
description: Create bowtie index for reference genome
keywords:
    - index
    - fasta
    - genome
    - reference
tools:
    - bowtie:
          description: |
              bowtie is a software package for mapping DNA sequences against
              a large reference genome, such as the human genome.
          homepage: http://bowtie-bio.sourceforge.net/index.shtml
          documentation: http://bowtie-bio.sourceforge.net/manual.shtml
          arxiv: arXiv:1303.3997
params:
    - outdir:
          type: string
          description: |
              The pipeline's output directory. By default, the module will
              output files into `$params.outdir/<SOFTWARE>`
    - publish_dir_mode:
          type: string
          description: |
              Value for the Nextflow `publishDir` mode parameter.
              Available: symlink, rellink, link, copy, copyNoFollow, move.
    - enable_conda:
          type: boolean
          description: |
              Run the module with Conda using the software specified
              via the `conda` directive
    - singularity_pull_docker_container:
          type: boolean
          description: |
              Instead of directly downloading Singularity images for use with Singularity,
              force the workflow to pull and convert Docker containers instead.
input:
    - fasta:
          type: file
          description: Input genome fasta file
output:
    - index:
          type: file
          description: Bowtie genome index files
          pattern: "*.ebwt"
    - version:
          type: file
          description: File containing software version
          pattern: "*.{version.txt}"
authors:
    - "@kevinmenden"
