# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-mag-1.1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - bioconda::fastqc=0.11.8   # update -> 0.11.9
  - bioconda::multiqc=1.9
  - bioconda::fastp=0.20.0 # -> 0.20.1
  - bioconda::megahit=1.2.9   # -> 1.2.9
  - bioconda::metabat2=2.15
  - bioconda::samtools>=1.10
  - bioconda::bowtie2>=2.3.5 # -> 2.4.1
  - bioconda::quast=5.0.2
  - bioconda::prodigal=2.6.3
  - bioconda::diamond>=0.9.24 # -> 2.0.0
  - conda-forge::r=3.6    # -> 4
  - conda-forge::biopython>=1.74  # -> 1.77
  - bioconda::krona=2.7.1
  - conda-forge::r-markdown>=1.0  # -> 1.1
  - conda-forge::r-ggplot2>=3.2.0 # -> 3.3.2
  - bioconda::busco=4.1.2
  - bioconda::nanoplot>=1.26.3  # -> 1.31.0
  - bioconda::filtlong=0.2.0
  - bioconda::porechop>=0.2.3_seqan2.1.1  # -> 0.2.4
  - bioconda::nanolyse=1.1.3
  - bioconda::spades>=3.13.1  # -> 3.14.0
#  - bioconda::centrifuge=1.0.4_beta
  - bioconda::cat>=4.6  # -> 5.1.2
  - bioconda::kraken2=2.0.8_beta
